### ISSUE TITLE
Questions about  Supplementary Table 5

### ISSUE THREAD

**Issue by ALEX95GOGO** [zjwzcx/GenNBV#2]
Thank you for your awesome work. I have a few questions regarding Supplementary Table 5. I probably misunderstand something there, so I hope you can help us figure it out/ 

1. Can you explain the occupancy threshold mentioned? I assume this is not a probability, as it should not exceed 1. If it is a log-odds value, the figures seem quite small.

2. Regarding the C' values—if these are in log odd, converting them back to probability suggests values over 0.9. Isn't that too high, making no difference between them?

I appreciate you taking the time to address these queries.

**Comment by zjwzcx** [comment]
Thanks for your attention! Here is my explanation :)

**Q2:**
In section 1.1 of our supplementary material, we mentioned we’d update the log-odd occupancy probability of that voxel by adding the value of C, where $C=\log\frac{p(z_j | v_i = 1)}{p(z_j | v_i = 0)}$.

In fact, there are only two cases for the measurement event: $z_j = 0$ or $z_j = 1$, right? Thus, if the measurement event $z_j$ (i.g., the voxel is passed through by the $j^{th}$ camera ray) happens, we’ll update the occupancy by adding the value of $C_1=\log\frac{p(z_j = 1 | v_i = 1)}{p(z_j = 1 | v_i = 0)}$. If it’s not passed, we’ll add the value $C_2 = \log\frac{p(z_j = 0 | v_i = 1)}{p(z_j = 0 | v_i = 0)}$. Obviously, the values of $C_1$ and $C_2$ can be designed depending on the accuracy of ray casting or other factors. Actually, $C’ = \frac{C_1}{C_2}$. We set the high incremental value for $C'$ (i.e., high confidence) because our experiments are based on the realistic simulator.

**Q1:**
Then we can set the threshold for cumulative C values to determine the occupancy state of each voxel.

Thanks for your issue. I’d like to update the detailed explanation to our newest arxiv version next week. If you have any questions, please let me know.

**Comment by ALEX95GOGO** [comment]
Hi, thank you for the quick response. I still have a few questions regarding this part.
 
The values for C' can be 5, 10, 20, and 40. It seems that using any one of these values can exceed the thresholds of 0.5, 1.0, 1.5, and 2.5. Therefore, I am a bit confused about why there are significant differences in the AUC, coverage ratio, and accuracy between these values.

![image](https://github.com/user-attachments/assets/ae3cdb4e-7c77-4c9f-a88b-9d45a9163297)

**Comment by zjwzcx** [comment]
> Hi, thank you for the quick response. I still have a few questions regarding this part.
> 
> The values for C' can be 5, 10, 20, and 40. It seems that using any one of these values can exceed the thresholds of 0.5, 1.0, 1.5, and 2.5. Therefore, I am a bit confused about why there are significant differences in the AUC, coverage ratio, and accuracy between these values.
> 
> ![image](https://private-user-images.githubusercontent.com/12646722/348066200-ae3cdb4e-7c77-4c9f-a88b-9d45a9163297.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTk5MjksIm5iZiI6MTcyMTExOTYyOSwicGF0aCI6Ii8xMjY0NjcyMi8zNDgwNjYyMDAtYWUzY2RiNGUtN2M3Ny00YzlmLWE4OGItOWQ0NWE5MTYzMjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA4NDcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwOTRjZjBlMjZjZTM1OWJhY2U0MzNjMDZjZmU0NWQzYjZkNWMzYjMwYjczMzZmNzlmMzlhZGRkNzVjOTgxNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ysRbVkCqchjz6vI1ucqW30P7-Qy_US9NJhQKcvMjJhE)

Thanks for your question! There may be a misunderstanding: $C'$ is just the ratio representing the confidence/weight of each measurement event, which is different from the value $C$ in Eq. 1.

Let me take a simplified example. 1) Let $C'=20$, where $C_1=1.0$, $C_2=-0.05$, occupancy_threshold=2.5. We initialize the occupancy state of a certain voxel as zero; 2) If we observe that one camera ray passes through this voxel, we'll update the occupancy state by adding $C_1=1.0$; 3) Thus, we need to observe the measurement event (i.e., the ray passes through the voxel) at least three times if we set occupancy threshold=2.5. 

**As for your question: In fact, the higher threshold requires denser scanning trajectories (to scan one area many times), ensures more accurate reconstruction results, and makes it more difficult to scan comprehensively.** 

However, the technical bottleneck of next-best-view planning for reconstruction is the completeness of scanning, instead of the density of scanning trajectory. Thus, we select the lower occupancy threshold in our framework.

**Comment by ALEX95GOGO** [comment]
Thank you very much for your answer! Our questions are solved.
